module OMOPCommonDataModel

import Dates
import DocStringExtensions

export CDMType

include("types.jl")
include("version.jl")

include("Generate/Generate.jl")
include("autogenerated.jl")
include("utils.jl")

end # end module OMOPCommonDataModel
