module OMOPCommonDataModel

import Dates
import DocStringExtensions

export CDMType

"""
An OMOP Common Data Model (CDM) type.
"""
abstract type CDMType end

const CDM_VERSION = v"5.1.3"
include("version.jl")

include("Generate/Generate.jl")

# the `src/autogenerated.jl file` is automatically generated by
# the `OMOPCommonDataModel.Generate.generate()`` function
include("autogenerated.jl")

end # end module OMOPCommonDataModel
